language: ruby
rvm:
  - 2.1.6
  - 2.2.2
addons:
  postgresql: "9.3"
before_install: gem install bundler -v 1.10.5
before_script:
  - cp spec/database.yml.travis spec/database.yml
script:
  - bundle exec rake spec
